name: Push to Main branche

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/push-main.yml'
      - 'package.json'
      - 'index.js'
      - 'src/**'
      - 'examples/**'
permissions:
  contents: read

jobs:
  crud_no_replica_and_replicaset:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ 16, 18, 20 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Node ${{ matrix.node }} OS ${{ matrix.os }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm test

  execute_fetch_request:
    needs: [ crud_no_replica_and_replicaset ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ 18, 20 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        test: [ execute ]
    name: Node ${{ matrix.node }} OS ${{ matrix.os }} ${{ matrix.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm run test:${{ matrix.test }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
